development:
  secret_key_base: f96589c09267c0bf05f5ae9070fd48bc63b228bd7047f4e772d67c6beb4d2d865bcd696f5d3684fa1fbc16070da56b62cf70b0ca8adf68bc38965aae4347ede0
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

test:
  secret_key_base: f96589c09267c0bf05f5ae9070fd48bc63b228bd7047f4e772d67c6beb4d2d865bcd696f5d3684fa1fbc16070da56b62cf70b0ca8adf68bc38965aae4347ede0

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>